# Generated by Django 5.2.4 on 2025-07-26 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("harga", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="Pesanan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("antri", "Antri"),
                            ("proses", "Proses"),
                            ("selesai", "Selesai"),
                        ],
                        default="antri",
                        max_length=10,
                    ),
                ),
                (
                    "meja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kafe_id.meja"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetailPesanan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumlah", models.PositiveIntegerField()),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kafe_id.menu"
                    ),
                ),
                (
                    "pesanan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kafe_id.pesanan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("waktu", models.DateTimeField(auto_now_add=True)),
                (
                    "meja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kafe_id.meja"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pesanan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kafe_id.user"
            ),
        ),
    ]
