# Generated by Django 5.2.4 on 2025-07-26 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kafe_id", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="harga",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="meja",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kafe_id.meja",
            ),
        ),
    ]
