# Generated by Django 5.2.4 on 2025-07-26 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kafe_id", "0002_alter_menu_harga_alter_user_meja"),
    ]

    operations = [
        migrations.AddField(
            model_name="pesanan",
            name="waktu",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
